### ISSUE TITLE
ActionSheetPicker is not dismissed

### ISSUE THREAD

**Issue by taoufik072** [TimCinel/ActionSheetPicker#120]
![img_0038](https://cloud.githubusercontent.com/assets/5896134/6325290/ab97425c-bb45-11e4-9702-605ec8a1c981.PNG)

i have an issue when calling a controller with presentViewController(Modal) , when i make a rotation i found the picker stay sticked even i select the action done and cancel , i tried to change dismissPicker method but i can't resolving my problem , please help ..

**Comment by skywinder** [comment]
This version is deprecated: use [**ActionSheetPicker-3.0**](https://github.com/skywinder/ActionSheetPicker-3.0) instead.
