### ISSUE TITLE
size popover

### ISSUE THREAD

**Issue by taoufik072** [TimCinel/ActionSheetPicker#121]
hey ,how can i change the size of my popover thx,
![img_0039](https://cloud.githubusercontent.com/assets/5896134/6326921/f43858f0-bb56-11e4-8065-5d198e99e6c0.PNG)

**Comment by skywinder** [comment]
This version is deprecated: use [**ActionSheetPicker-3.0**](https://github.com/skywinder/ActionSheetPicker-3.0) instead.
