### ISSUE TITLE
ActionSheetPickerCustomPickerDelegate

### ISSUE THREAD

**Issue by Nilesh04** [TimCinel/ActionSheetPicker#127]
I am using custom picker. It works well till iOS 8.4
But in iOS 9 I am getting issue in picker it is showing ... in place of text.
PFA. If anyone finds solution then Please revert back.
![screen shot 2015-09-22 at 3 46 42 pm](https://cloud.githubusercontent.com/assets/11361817/10015959/2c1d5cd0-6141-11e5-8dad-d4ac4b38607c.png)

**Comment by skywinder** [comment]
PLease, use https://github.com/skywinder/ActionSheetPicker-3.0 instad. If this issue related with ActionSheetPicker-3.0 - please, open issue there. Probably related with https://github.com/skywinder/ActionSheetPicker-3.0/issues/213

**Comment by Nilesh04** [comment]
I am using "https://github.com/skywinder/ActionSheetPicker-3.0"
In this I am getting issue ..
