### ISSUE TITLE
Toolbar Buttons Tint Color iOS 9

### ISSUE THREAD

**Issue by nadagamal** [TimCinel/ActionSheetPicker#131]
Hi,
I had an issue on change the tint color of (Done and cancel)  buttons of UIToolbar. The text color always clear. the issue is happened on iOS 9 devices.

Thank you,

**Comment by skywinder** [comment]
This version is deprecated: use ActionSheetPicker-3.0 instead.
https://github.com/skywinder/ActionSheetPicker-3.0
