### ISSUE TITLE
Toolbar background color

### ISSUE THREAD

**Issue by miledaoun** [TimCinel/ActionSheetPicker#133]
Hello

This is not actually an issue more than a request

is it possible to remove the background of the toolbar by adding the below lines or by making it dynamic by adding a new property

I added the below lines myself to achieve that in the abstract picker line 471

[pickerToolbar setTranslucent:YES];
    pickerToolbar.barStyle = UIBarStyleBlack;
    pickerToolbar.backgroundColor = [UIColor clearColor];
    [pickerToolbar setBackgroundImage:[UIImage new]
                   forToolbarPosition:UIToolbarPositionAny
                           barMetrics:UIBarMetricsDefault];

Many thanks
![screen shot 2018-09-03 at 5 41 33 pm](https://user-images.githubusercontent.com/29977208/44992676-a1dc5600-afa0-11e8-8ad9-3f6fde615de1.png)

**Comment by skywinder** [comment]
This version is deprecated: use ActionSheetPicker-3.0 instead.
https://github.com/skywinder/ActionSheetPicker-3.0
